<?php

namespace ContainerEIbjxf9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPuebaTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\PuebaType' shared autowired service.
     *
     * @return \App\Form\PuebaType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/PuebaType.php';

        return $container->privates['App\\Form\\PuebaType'] = new \App\Form\PuebaType();
    }
}
