<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEIbjxf9\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEIbjxf9/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEIbjxf9.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEIbjxf9\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEIbjxf9\App_KernelDevDebugContainer([
    'container.build_hash' => 'EIbjxf9',
    'container.build_id' => 'f73be6fb',
    'container.build_time' => 1692236142,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEIbjxf9');
