<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'index' => [[], ['_controller' => 'App\\Controller\\PageController::index'], [], [['text', '/']], [], [], []],
    'contact-v1' => [[], ['_controller' => 'App\\Controller\\PageController::contactoV1'], [], [['text', '/contacto-v1']], [], [], []],
    'contact-v2' => [[], ['_controller' => 'App\\Controller\\PageController::contactoV2'], [], [['text', '/contacto-v2']], [], [], []],
    'contact-v3' => [[], ['_controller' => 'App\\Controller\\PageController::contactoV3'], [], [['text', '/contacto-v3']], [], [], []],
    'post_create' => [[], ['_controller' => 'App\\Controller\\PostController::create'], [], [['text', '/post/crear']], [], [], []],
    'post_edit' => [['id'], ['_controller' => 'App\\Controller\\PostController::editar'], [], [['text', '/editar'], ['variable', '/', '[^/]++', 'id', true], ['text', '/post']], [], [], []],
];
